export const mockBooks = [
  {
    id: 1,
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: ["Fiction", "Horror"],
    publishDate: "1960-07-11",
    pages: 281,
    volume: 1,
    totalVolume: 4,
    averageRating: 4.8,
    userRatings: [5, 4, 5, 4, 5],
    description: "A gripping, heart-wrenching tale of racial injustice and moral growth in the Deep South. A gripping, heart-wrenching tale of racial injustice and moral growth in the Deep South. A gripping, heart-wrenching tale of racial injustice and moral growth in the Deep South.",
    image: "https://example.com/images/to-kill-a-mockingbird.jpg",
    reviews: [
      {
        user: "John Doe",
        comment: "A timeless classic!",
        rating: 5,
      },
      {
        user: "Jane Smith",
        comment: "Beautifully written and thought-provoking.",
        rating: 4,
      },
    ],
  },
  {
    id: 2,
    name: "1984",
    author: "George Orwell",
    genre: ["Science Fiction", "Dystopian"],
    publishDate: "1949-06-08",
    pages: 328,
    volume: 1,
    totalVolume: 1,
    averageRating: 4.7,
    userRatings: [5, 5, 4, 5, 4],
    description: "A chilling dystopian novel that explores the dangers of totalitarianism and extreme surveillance.",
    image: "https://example.com/images/1984.jpg",
    reviews: [
      {
        user: "Alice Johnson",
        comment: "Chillingly relevant even today.",
        rating: 5,
      },
      {
        user: "Bob Brown",
        comment: "A masterpiece in every sense.",
        rating: 4,
      },
    ],
  },
  {
    id: 3,
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: ["Classic", "Tragedy"],
    publishDate: "1925-04-10",
    pages: 180,
    volume: 1,
    totalVolume: 1,
    averageRating: 4.6,
    userRatings: [4, 5, 4, 5, 4],
    description: "A tragic story of love, ambition, and the American Dream set in the Jazz Age.",
    image: "https://example.com/images/the-great-gatsby.jpg",
    reviews: [
      {
        user: "Emily White",
        comment: "Captures the essence of the roaring twenties.",
        rating: 5,
      },
      {
        user: "David Green",
        comment: "A bit overrated, but still good.",
        rating: 4,
      },
    ],
  },
  {
    id: 4,
    name: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: ["Fantasy", "Adventure"],
    publishDate: "1937-09-21",
    pages: 310,
    volume: 1,
    totalVolume: 1,
    averageRating: 4.8,
    userRatings: [5, 5, 5, 4, 4],
    description: "A thrilling adventure of Bilbo Baggins, a hobbit who discovers courage and friendship on an epic quest.",
    image: "https://example.com/images/the-hobbit.jpg",
    reviews: [
      {
        user: "Chris Lee",
        comment: "An enchanting tale of adventure and bravery!",
        rating: 5,
      },
      {
        user: "Samantha Ray",
        comment: "A delightful read with memorable characters.",
        rating: 4,
      },
    ],
  },
  {
    id: 5,
    name: "Pride and Prejudice",
    author: "Jane Austen",
    genre: ["Classic", "Romance"],
    publishDate: "1813-01-28",
    pages: 279,
    volume: 1,
    totalVolume: 1,
    averageRating: 4.7,
    userRatings: [5, 4, 4, 5, 5],
    description: "A witty exploration of manners, marriage, and society in Regency-era England.",
    image: "https://example.com/images/pride-and-prejudice.jpg",
    reviews: [
      {
        user: "Laura White",
        comment: "A perfect blend of romance and satire!",
        rating: 5,
      },
      {
        user: "James Carter",
        comment: "Timeless characters and engaging dialogue.",
        rating: 4,
      },
    ],
  },
];

export const mockUsers = [
  {
    username: "booklover123",
    firstName: "Alex",
    lastName: "Smith",
    age: 25,
    email: "alex.smith@example.com",
    image: "https://example.com/images/user1.jpg",
    books: [
      {
        bookName: "To Kill a Mockingbird",
        bookStatus: "Read",
        bookReviewed: true,
        bookReview: "A deeply impactful story that resonates even today.",
      },
      {
        bookName: "1984",
        bookStatus: "Want to Read",
        bookReviewed: false,
        bookReview: "",
      },
    ],
  },
  {
    username: "readerqueen",
    firstName: "Emily",
    lastName: "Johnson",
    age: 30,
    email: "emily.johnson@example.com",
    image: "https://example.com/images/user2.jpg",
    books: [
      {
        bookName: "Pride and Prejudice",
        bookStatus: "Currently Reading",
        bookReviewed: true,
        bookReview: "A classic romance with sharp wit and brilliant characters.",
      },
      {
        bookName: "The Hobbit",
        bookStatus: "Read",
        bookReviewed: true,
        bookReview: "An epic adventure that captures the imagination.",
      },
    ],
  },
];

export const genres = [
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Mystery",
  "Fantasy",
  "Biography",
  "Adventure",
  "Crime",
  "Horror",
  "Classic",
  "Tragedy",
  "Dystopian",
  "Romance",
  "Historical Fiction",
  "Thriller",
];
